
@startuml


class CustomerController{
    -CatalogService catalogService
    +getCatalog()
}

CustomerController --> CatalogService
CatalogService --|> CatalogRepository
CatalogRepository --|> Database
@enduml
