-- Up Migration
INSERT INTO products (title, description, price) VALUES
('Wireless Noise-Cancelling Headphones', 'Over-ear headphones with active noise cancellation, 30-hour battery life, and premium sound quality.', 89.99),
('Mechanical Keyboard', 'Compact tenkeyless mechanical keyboard with Cherry MX Blue switches and RGB backlighting.', 74.95),
('USB-C Hub 7-in-1', 'Multiport adapter with HDMI, 3x USB-A, SD card reader, USB-C power delivery, and 3.5mm audio.', 34.99),
('Ergonomic Office Chair', 'Adjustable lumbar support, breathable mesh back, and 4D armrests for all-day comfort.', 299.00),
('Standing Desk Converter', 'Sit-stand desktop riser with smooth height adjustment and spacious work surface.', 149.99),
('Webcam 1080p', 'Full HD webcam with built-in stereo microphone and auto light correction for video calls.', 49.99),
('Portable SSD 1TB', 'Ultra-compact solid state drive with USB 3.2 Gen 2 and read speeds up to 1050MB/s.', 109.99),
('Monitor Light Bar', 'LED desk lamp that clips to any monitor, reduces glare, and has wireless brightness control.', 39.99),
('Laptop Stand', 'Adjustable aluminum laptop riser with six height settings and foldable design for portability.', 29.99),
('Desk Pad XL', 'Extra-large 36x18 inch water-resistant desk mat with non-slip rubber base and smooth surface.', 24.99),
('Smart LED Bulb 4-Pack', 'WiFi-enabled color-changing bulbs compatible with Alexa and Google Home, 800 lumens each.', 32.99),
('Mechanical Pencil Set', 'Premium drafting pencils in 0.3, 0.5, and 0.7mm with metal grip and twist-advance mechanism.', 18.50),
('Notebook A5 Hardcover', 'Dot-grid pages, lay-flat binding, 200 pages of 90gsm paper, with elastic closure.', 14.99),
('Wireless Charging Pad', 'Qi-certified 15W fast wireless charger compatible with all Qi-enabled phones and earbuds.', 22.99),
('Cable Management Box', 'Large desktop organizer to hide power strips and cables, with six side openings.', 19.99),
('Blue Light Glasses', 'Anti-blue light filtering lenses in lightweight TR90 frames to reduce eye strain.', 27.99),
('Desk Organizer', 'Bamboo multi-compartment organizer with pen holder, phone slot, and removable dividers.', 21.99),
('Indoor Plant Pot Set', 'Set of 3 self-watering ceramic pots in white matte finish, with drainage and saucers.', 36.00),
('Espresso Maker', 'Stovetop moka pot for 6 cups, polished aluminum with heat-resistant handle.', 29.95),
('Pour-Over Coffee Set', 'Borosilicate glass dripper, matching carafe, and stainless steel gooseneck kettle.', 54.99),
('Insulated Travel Mug', '20oz double-wall vacuum insulated stainless steel, keeps drinks hot 12 hours or cold 24 hours.', 31.99),
('Reusable Water Bottle', '32oz wide-mouth Tritan plastic bottle with flip lid, carrying loop, and measurement markings.', 16.99),
('Cast Iron Skillet 10"', 'Pre-seasoned cast iron pan for oven, stovetop, grill, and campfire use.', 44.99),
('Chef''s Knife 8"', 'High-carbon German steel blade with full tang and triple-riveted ergonomic handle.', 59.99),
('Cutting Board Set', 'Set of 3 bamboo cutting boards with juice groove and handle, in small, medium, and large.', 28.99),
('Digital Kitchen Scale', 'Precision food scale with 0.1g accuracy, tare function, and backlit LCD display.', 17.99),
('Silicone Baking Mat 2-Pack', 'Half-sheet non-stick reusable baking mats, heat resistant to 480°F.', 13.99),
('Handheld Milk Frother', 'Battery-powered frother with stainless steel whisk for lattes, cappuccinos, and matcha.', 9.99),
('Spice Rack 20-Jar', 'Wall-mounted magnetic spice rack with 20 labeled round jars and strong magnets.', 42.00),
('Yoga Mat', 'Extra-thick 6mm non-slip TPE mat with carrying strap, 72x24 inches.', 38.99),
('Resistance Band Set', 'Five latex bands in varying resistance levels with door anchor, handles, and ankle straps.', 24.99),
('Foam Roller', '18-inch high-density EVA foam roller for muscle recovery and myofascial release.', 19.99),
('Jump Rope', 'Adjustable speed rope with ball bearings, foam handles, and digital counter.', 14.99),
('Dumbbell Set 5-25lb', 'Hex rubber dumbbell pairs in 5, 10, 15, 20, and 25 pounds with storage rack.', 189.00),
('Pull-Up Bar', 'Doorframe pull-up bar with foam grips, no screws required, holds up to 300 lbs.', 34.99),
('Running Belt', 'Slim waist pack with bounce-free fit, water-resistant zipper, and phone window.', 18.99),
('Wool Beanie', 'Slouchy knit hat in 100% merino wool, one size fits most, in heather grey.', 22.00),
('Canvas Tote Bag', 'Heavy-duty 12oz cotton canvas tote with 22-inch handles and interior zip pocket.', 15.99),
('Leather Wallet', 'Slim bifold genuine leather wallet with 6 card slots, bill compartment, and RFID blocking.', 34.99),
('Stainless Steel Watch', 'Minimalist 40mm case with sapphire crystal, mesh bracelet, and 5ATM water resistance.', 129.00),
('Sunglasses Polarized', 'Classic aviator style with polarized UV400 lenses and spring hinge temples.', 29.99),
('Scented Candle Set', 'Set of 4 soy wax candles in amber jars: cedar, vanilla, eucalyptus, and sea salt.', 32.00),
('Throw Blanket', '50x60 inch chunky knit sherpa blanket, machine washable, in warm oatmeal.', 44.99),
('Picture Frame Set', 'Set of 6 black gallery frames in 4x6, 5x7, and 8x10, with mat options and wall hardware.', 37.99),
('Whiteboard 24x36"', 'Magnetic dry-erase board with aluminum frame, marker tray, and mounting hardware.', 54.99),
('Wireless Mouse', 'Ergonomic 2.4GHz wireless mouse with silent clicks, 1600 DPI, and 18-month battery life.', 27.99),
('Screen Cleaning Kit', 'Microfiber cloth and alcohol-free spray solution for monitors, phones, and glasses.', 8.99),
('Power Strip Surge Protector', '6-outlet surge protector with 3 USB-A ports, 4-foot braided cord, and 1080 joule protection.', 25.99),
('Cable Clips 20-Pack', 'Self-adhesive silicone cable organizers for desk, nightstand, and wall routing.', 7.99),
('Book Stand', 'Adjustable bamboo book and tablet holder with page clips, folds flat for storage.', 23.99);

-- Down Migration
DELETE FROM products WHERE title IN (
  'Wireless Noise-Cancelling Headphones', 'Mechanical Keyboard', 'USB-C Hub 7-in-1',
  'Ergonomic Office Chair', 'Standing Desk Converter', 'Webcam 1080p', 'Portable SSD 1TB',
  'Monitor Light Bar', 'Laptop Stand', 'Desk Pad XL', 'Smart LED Bulb 4-Pack',
  'Mechanical Pencil Set', 'Notebook A5 Hardcover', 'Wireless Charging Pad',
  'Cable Management Box', 'Blue Light Glasses', 'Desk Organizer', 'Indoor Plant Pot Set',
  'Espresso Maker', 'Pour-Over Coffee Set', 'Insulated Travel Mug', 'Reusable Water Bottle',
  'Cast Iron Skillet 10"', 'Chef''s Knife 8"', 'Cutting Board Set', 'Digital Kitchen Scale',
  'Silicone Baking Mat 2-Pack', 'Handheld Milk Frother', 'Spice Rack 20-Jar', 'Yoga Mat',
  'Resistance Band Set', 'Foam Roller', 'Jump Rope', 'Dumbbell Set 5-25lb', 'Pull-Up Bar',
  'Running Belt', 'Wool Beanie', 'Canvas Tote Bag', 'Leather Wallet', 'Stainless Steel Watch',
  'Sunglasses Polarized', 'Scented Candle Set', 'Throw Blanket', 'Picture Frame Set',
  'Whiteboard 24x36"', 'Wireless Mouse', 'Screen Cleaning Kit', 'Power Strip Surge Protector',
  'Cable Clips 20-Pack', 'Book Stand'
);
